#!/usr/bin/env bash
#transfers a file and raises error if args = lt 4
#
if [ $# -lt 4 ]
then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
else
	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~
fi

