#!/usr/bin/env bash
#making a clock with a while loop

hours=0
minutes=1

while [ $hours -le 12 ]; do
	echo "Hour: $hours"
	while [ $minutes -le 59 ]; do
		echo "$minutes"
		((minutes++))
	done
	minutes=1
	((hours++))
done
